sudo:required
services:
    - docker

before_install:
    - docker build -t docker-react-img -f Dockerfile.dev .

script:
    - docker run -e CI=true docker-react-img npm run test -- --coverage

